secret:
  create: true
  data:
    cloud: |
      AZURE_SUBSCRIPTION_ID=302a84fc-f3d2-49e8-9fea-441314a9b113
      AZURE_TENANT_ID=e9a964b9-740e-40ba-8365-319d2086e883
      AZURE_CLIENT_ID=56b86b83-1db4-4bb5-baea-42c889746810
      AZURE_CLIENT_SECRET="jE/d1HM:J2UzWtoF0K8#egL5NTV4sxY-Si"
      AZURE_RESOURCE_GROUP=mc_numbers-test-aks_numbers-test-aks_westeurope
      AZURE_CLOUD_NAME=AzurePublicCloud
