repositories:
  - name: bitnami
    url: https://charts.bitnami.com/bitnami
  - name: jetstack
    url: https://charts.jetstack.io
  - name: vmware-tanzu
    url: https://vmware-tanzu.github.io/helm-charts
