secret:
  create: true
  data:
    azure.json: |
      {
        "tenantId": "e9a964b9-740e-40ba-8365-319d2086e883",
        "subscriptionId": "302a84fc-f3d2-49e8-9fea-441314a9b113",
        "resourceGroup": "numbers-prod-zone",
        "aadClientId": "56b86b83-1db4-4bb5-baea-42c889746810",
        "aadClientSecret": "jE/d1HM:J2UzWtoF0K8#egL5NTV4sxY-Si"
      }
