"""empty message

Revision ID: 758aa01f1593
Revises: 
Create Date: 2021-08-22 00:33:42.360922

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "758aa01f1593"
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "item",
        sa.Column("id_", sa.Integer(), nullable=False),
        sa.Column("name", sa.Text(), nullable=False),
        sa.PrimaryKeyConstraint("id_"),
        sa.UniqueConstraint("name"),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("item")
    # ### end Alembic commands ###
