name: Deploy MagnusAPI test environment
on: [push]
jobs:
  Deploy:
    env:
      ARM_CLIENT_ID: ${{ secrets.ARM_CLIENT_ID }}
      ARM_CLIENT_SECRET: ${{ secrets.ARM_CLIENT_SECRET }}
      ARM_SUBSCRIPTION_ID: ${{ secrets.ARM_SUBSCRIPTION_ID }}
      ARM_TENANT_ID: ${{ secrets.ARM_TENANT_ID }}
    environment: test
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v2
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v1
      - name: Test Terraform
        run: |
          RELEASE_VERSION=${GITHUB_REF#refs/*/}
          terraform init
          terraform apply -auto-approve -var "branch=${RELEASE_VERSION}"
        working-directory: terraform/environments/numbers-test/azure-webfarm
